### ISSUE TITLE
When i try to use a extension js, it shows that 'Scanner' is not defined 

### ISSUE THREAD

**Issue by tcsecchen** [dzonerzy/goWAPT#4]
i use the command 
gowapt -u "192.168.1.89/aaa/FUZZ"  -w wordlist/general/common.txt  -x plugins/xss-reflect.js

then,it shows that 'Scanner' is not defined ,how can i use the js extension files 

thank u

**Comment by dzonerzy** [comment]
Hi @tcsecchen ,

You are mixing default mode with scanner mode, as stated in the readme the **-x** switch is used to run a single plugin which act like a proxy between the target and the tool, instead the **xss-reflect.js** is a plugin meant to be used with scanner mode, so no fuzzing will be performed (you don't need to use neither **-w** nor **-u**) , if you want to scan your target with xss-reflect these are the correct switches:

> gowapt --from-proxy --scanner --plugin-dir plugin/

Where **--from-proxy** will receive a raw request from a proxy, you may use burpsuite, **--scanner** will initialize the Scanner module (**Scanner object**) and **--plugin-dir** is the plugin where **xss-reflect.js** resides.

Let me know if this works for you.

Regards,
Daniele

**Comment by tcsecchen** [comment]
yeah，it works！
it‘s very convenient，thank u very much

**Comment by dzonerzy** [comment]
I'm closing this issue! 👍 Thanks for using GoWAPT
